Dev attribution info
ldbv-by/bav4-nomigration pull request #213
Opened 2021-04-13 17:35 UTC by EnBakir

A component that shows information about the attribution of the basemap(s).

2021-04-14 05:55 UTC, thiloSchlemmer commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +			geoResource.attribution ? this._content = geoResource.attribution : this._content = 'No data available';
'No data available' is good candidate for the TranslationService, i guess.

2021-04-14 06:14 UTC, thiloSchlemmer commented on test/modules/footer/components/attributionInfo/AttributionInfo.test.js
> +			expect(element.shadowRoot.querySelector('p').innerHTML).toContain('No data available');
Albeit the attribution-property is not already implemented and a valid content structure could change...i would prefer, to have a test for a simple but valid attribution-content (layer.attribution !== null -> layer.attribution='FooBarBaz' should be OK for now).

2021-04-14 06:15 UTC, thiloSchlemmer requested changes
See inline comments

2021-04-14 06:40 UTC, taulinger reviewed
Well on track!
You could also already provide the zoom-level information from the store, we will need it for zoom-level dependent attributions.

2021-04-14 06:40 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +		this._content = null;
Avoid unnecessary private fields, which makes your code more resistant to unwanted side-effects

2021-04-15 13:30 UTC, taulinger reviewed
Nice, I will extend the georesource domain classes now.
In the meantime you could provide the zoom-level information from the store, we will need it for zoom-level dependent attributions.

2021-04-16 05:47 UTC, thiloSchlemmer approved these changes

2021-04-16 08:46 UTC, taulinger commented
@EnBakir Added the attribution definition and its access in `GeoResources`. Please have look at the attribution's `@typedef` doc to get an idea about guaranteed and optionally values

2021-04-22 12:26 UTC, EnBakir commented
The `AttributionInfo.js` is now using the `georesource.getAttribution(zoom)` Method. Next steps are: 

1. Refactoring: Move `attributionInfo` to `map/components` folder
2. Extend `BaseLayerInfo.js`

2021-04-22 12:46 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +			}
Have a look @ attribution typedef in `geoResources.js`.
An attribution object MAY also contain an `url` property. In this case, we need an anchor here.

2021-04-24 11:35 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +				}
The only difference in each case is the appended semicolon. Can we reduce the redundant code here (-> DRY)?

2021-04-24 11:35 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +		if (typeof active !== undefined && active.length > 0) {
Unneeded check: `active` is guaranteed not to be null or undefined by the layers reducer

2021-04-24 11:35 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +					}
Do we really need `<p>` elements in this case?

2021-04-24 11:35 UTC, taulinger commented on src/modules/footer/components/attributionInfo/AttributionInfo.js
> +			}
No need to check for an empty array. `geoResource.getAttribution()` makes sure you will either get `null` or an array with at least one element

2021-04-24 11:35 UTC, taulinger commented on test/modules/footer/components/attributionInfo/AttributionInfo.test.js
> +		it('updates BaseLayerInfo component', async ()  => {
wrong label (BaseLayerInfo) also in line 183

2021-04-28 07:58 UTC, taulinger commented on src/modules/map/components/attributionInfo/AttributionInfo.js
> +		const geoResource = active[0] ?  this._georesourceService.byId(active[0].id) : null;
Sorry, did not see this the last time:
In contrast to the base layer info (where we take the current base layer only), here we have to display the attribution for **all active AND visible layers**

2021-04-29 10:12 UTC, alsturm approved these changes
well done! added style, moved it to footer.

2021-04-30 09:54 UTC, taulinger commented
@alsturm Can we improve the layout for "long" attributions? 
For instance:
localhost:8080?l=atkis,9d0e3859-be17-4a40-b439-1ba19b45fbb8,5d4af972-fa72-48e0-a8c1-55d0782e540a,d8f6e9a6-d5ef-4234-a77c-e6253f279e57,26d2b2b8-3944-4a49-aec2-59f827d9aa9e,a818e80e-78b7-4b21-8c15-d5f8abe6c420

2021-04-30 10:09 UTC, taulinger reviewed
Let's remove the fallback (see inline comment)

2021-04-30 10:09 UTC, taulinger commented on src/modules/map/components/attributionInfo/AttributionInfo.js
>  		}
I think we can remove the complete fallback case now, it's not needed anymore...

2021-04-30 16:31 UTC, taulinger reviewed
Thx, let's wait for @alsturm  UI optimizations...
Maybe we have to add additional functionality like shortening the attribution string and
a toggle function. We will have a look at this next week....

2021-05-04 16:21 UTC, taulinger reviewed
@alsturm Nice proceedings
- Can we improve the formatting of line break (see screenshot)
For instance:
localhost:8080?l=atkis,9d0e3859-be17-4a40-b439-1ba19b45fbb8,5d4af972-fa72-48e0-a8c1-55d0782e540a,d8f6e9a6-d5ef-4234-a77c-e6253f279e57,26d2b2b8-3944-4a49-aec2-59f827d9aa9e,a818e80e-78b7-4b21-8c15-d5f8abe6c420

- if we show a title for opening the full content, we also need one for closing.... maybe we just name it "show all" and "close"

2021-05-05 12:26 UTC, taulinger approved these changes
Looks good now 👍

2021-05-05 12:27 UTC, taulinger commented
Let's merge it ...

2021-05-05 12:29 UTC, merged