Dev share ui
ldbv-by/bav4-nomigration pull request #252
Opened 2021-05-07 12:57 UTC by EnBakir

Implemented the share toolbox menu.

2021-05-11 08:54 UTC, taulinger reviewed
Nice proceedings!

@alsturm Does it make sense to add and include a common CSS for all ToolContainer?

2021-05-11 08:54 UTC, taulinger commented on src/modules/menu/components/toolBar/ToolBar.js
>  		const translate = (key) => this._translationService.translate(key);
Don't forget to add the test in 
`it('toggles and switches the tools'`

2021-05-11 08:54 UTC, taulinger commented on src/modules/toolbox/components/shareToolContent/ShareToolContent.js
> +				this._root.querySelector('.preview_button').classList.add('disabled-preview');
No test for this path

2021-06-18 08:08 UTC, taulinger requested changes
The generated URL is not always in sync with the current state.
E.g. the user changes the position of the map
while the  ShareToolContent is active.

2021-07-14 12:28 UTC, thiloSchlemmer approved these changes

2021-07-14 12:29 UTC, thiloSchlemmer approved these changes

2021-07-14 12:30 UTC, taulinger approved these changes

2021-07-14 12:32 UTC, taulinger commented
We should convert it to a PR not until @alsturm has optimized the layout.

2021-07-15 13:15 UTC, thiloSchlemmer approved these changes

2021-07-16 09:54 UTC, taulinger submitted a review, later dismissed
Almost done, see inline comments ...

2021-07-16 09:54 UTC, taulinger commented on src/modules/toolbox/components/shareToolContent/assets/envelope-solid.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
@alsturm License is missing

2021-07-16 10:50 UTC, alsturm submitted a review, later dismissed

2021-07-19 05:56 UTC, thiloSchlemmer approved these changes

2021-07-20 08:23 UTC, taulinger reviewed
We now have a different approach of when to show which kind of share possibility.
So let's start a round of reviews...

2021-07-20 08:43 UTC, thiloSchlemmer approved these changes

2021-07-20 09:05 UTC, merged